export const USER_MODEL_CONSTANTS = {
  MAX_USERNAME_LENGTH: 30,
  MIN_USERNAME_LENGTH: 3,
  MAX_EMAIL_LENGTH: 254,
  ID_LENGTH: 26,
};

export const PASSWORD_DATA_CONSTANTS = {
  MAX_PASSWORD_LENGTH: 100,
  MIN_PASSWORD_LENGTH: 8,
  SALT_LENGTH: 16,
  HASH_ALGORITHM: "sha256",
  HASH_ITERATIONS: 10000,
  HASH_KEY_LENGTH: 64,
};
